"""Build a deterministic missing-data assumptions and treatment-governance audit."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd

EVIDENCE = "synthetic_demo_not_empirical_evidence"
MECHANISM_STATUS = "not_inferred_by_gazeforge"
TREATMENT_STATUS = "not_selected_by_gazeforge"
SOURCE_CLASSES = {
    "observed",
    "acquisition_unavailable",
    "partial_observation",
    "design_absence",
    "undefined_derived_metric",
    "right_censored_event",
}


def _write_json(path: Path, payload: Any) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _source_registry() -> pd.DataFrame:
    rows = [
        ("S01", "P01", "T01", "claim_dwell_ms", "observed", False),
        ("S02", "P01", "T02", "claim_dwell_ms", "acquisition_unavailable", True),
        ("S03", "P02", "T03", "claim_dwell_ms", "partial_observation", True),
        ("S04", "P02", "T04", "disclosure_dwell_ms", "design_absence", False),
        ("S05", "P03", "T05", "fixation_rate_per_s", "undefined_derived_metric", False),
        ("S06", "P03", "T06", "first_fixation_latency_ms", "right_censored_event", False),
    ]
    return pd.DataFrame(
        rows,
        columns=(
            "source_id",
            "participant_id",
            "trial_id",
            "outcome_id",
            "source_class",
            "eligible_for_missingness_mechanism_assessment",
        ),
    )


def _mechanism_questions() -> pd.DataFrame:
    rows = [
        (
            "M01",
            "Is the unavailable measurement generated by the experimental design?",
            "design registry",
        ),
        (
            "M02",
            "Is missingness associated with prespecified observed participant/trial variables?",
            "observed covariates + grouped diagnostics",
        ),
        (
            "M03",
            "Could the unobserved outcome affect its probability of being unavailable?",
            "substantive theory + sensitivity assumptions",
        ),
        (
            "M04",
            "Is missingness clustered by participant, stimulus, session, or condition?",
            "group-aware summaries",
        ),
        (
            "M05",
            "Would the proposed missing-data treatment change the target estimand?",
            "estimand + denominator flow + treatment specification",
        ),
    ]
    out = pd.DataFrame(rows, columns=("question_id", "question", "evidence_needed"))
    out["mcar_mar_mnar_conclusion"] = MECHANISM_STATUS
    out["requires_study_specific_assessment"] = True
    return out


def _treatment_registry() -> pd.DataFrame:
    rows = [
        ("complete_case_analysis", "subset decision"),
        ("single_imputation", "imputation"),
        ("multiple_imputation", "imputation"),
        ("inverse_probability_weighting", "weighting"),
        ("joint_model", "model-based"),
        ("pattern_mixture_sensitivity", "sensitivity"),
        ("selection_model_sensitivity", "sensitivity"),
        ("survival_censoring_model", "time-to-event"),
    ]
    out = pd.DataFrame(rows, columns=("strategy", "family"))
    out["selection_status"] = TREATMENT_STATUS
    out["selected_automatically"] = False
    return out


def _separation_ledger() -> pd.DataFrame:
    rows = [
        ("P01", "T02", True, "acquisition_unavailable", "retained_missing"),
        ("P02", "T03", True, "partial_observation", "retained_after_review"),
        ("P02", "T04", False, "design_absence", "not_applicable_for_outcome"),
        ("P03", "T05", False, "undefined_derived_metric", "retained_undefined"),
        ("P03", "T06", False, "right_censored_event", "retained_censored"),
        ("P04", "T07", True, "observed", "excluded_after_review"),
    ]
    return pd.DataFrame(
        rows,
        columns=("participant_id", "trial_id", "qc_flag", "source_class", "review_decision"),
    )


def _sensitivity_handoff() -> pd.DataFrame:
    rows = [
        ("H01", "primary missing-data strategy", True),
        ("H02", "complete-case sensitivity", True),
        ("H03", "alternative missing-data model", True),
        ("H04", "MNAR-oriented sensitivity", False),
    ]
    out = pd.DataFrame(
        rows,
        columns=(
            "handoff_id",
            "analysis_variant",
            "same_estimand_required_for_direct_comparison",
        ),
    )
    out["execution_status"] = "not_executed_by_example"
    return out


def _reporting_language() -> pd.DataFrame:
    rows = [
        (
            "mechanism",
            "Observed data did not by themselves establish an MCAR, MAR, or MNAR mechanism.",
            "The software determined that missingness was MAR.",
        ),
        (
            "complete_case",
            "Complete-case analysis, if used, was an explicit analysis strategy.",
            "Rows with missing values were cleaned out before analysis.",
        ),
        (
            "imputation",
            "Any imputation method was prespecified and implemented in specialist software.",
            "Missing gaze values were automatically filled.",
        ),
        (
            "exclusion",
            "Missingness, QC flags, and reviewed exclusions were retained separately.",
            "Missing trials were excluded because they were invalid.",
        ),
        (
            "censoring",
            "Right-censored no-event latency remained a censoring state.",
            "No-fixation trials were missing and removed.",
        ),
        (
            "sensitivity",
            (
                "Missing-data sensitivity variants were reported without replacing "
                "the primary estimand."
            ),
            "The most favourable missing-data specification became the main result.",
        ),
    ]
    return pd.DataFrame(rows, columns=("topic", "claim_safe_wording", "avoid_wording"))


def _readme() -> str:
    return """# Missing-data assumptions and treatment audit

This deterministic teaching bundle is `synthetic_demo_not_empirical_evidence`.
It does not infer MCAR, MAR, or MNAR and does not select complete-case analysis,
imputation, weighting, joint modelling, sensitivity models, survival modelling,
GLM/GLMM, SEM, Bayesian, or another statistical treatment.

Use the denominator/exposure/censoring clinic first for observation-state mechanics.
This bundle documents assumptions and hands treatment selection to specialist statistics.
"""


def run(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    source = _source_registry()
    questions = _mechanism_questions()
    treatments = _treatment_registry()
    separation = _separation_ledger()
    sensitivity = _sensitivity_handoff()
    reporting = _reporting_language()

    tables = {
        "01_missing_data_source_registry.csv": source,
        "02_mechanism_assumption_questions.csv": questions,
        "03_analysis_treatment_registry.csv": treatments,
        "04_exclusion_missingness_separation.csv": separation,
        "05_sensitivity_handoff.csv": sensitivity,
        "06_reporting_language.csv": reporting,
    }
    for name, table in tables.items():
        table.to_csv(output_dir / name, index=False)

    if set(source["source_class"]) != SOURCE_CLASSES:
        raise RuntimeError("Source-class teaching coverage changed.")
    if questions["mcar_mar_mnar_conclusion"].ne(MECHANISM_STATUS).any():
        raise RuntimeError("The example must not infer MCAR/MAR/MNAR.")
    if treatments["selection_status"].ne(TREATMENT_STATUS).any():
        raise RuntimeError("The example must not select a statistical treatment.")
    if treatments["selected_automatically"].astype(bool).any():
        raise RuntimeError("No treatment may be selected automatically.")

    missing = separation["source_class"].eq("acquisition_unavailable")
    if separation.loc[missing, "review_decision"].eq("excluded_after_review").any():
        raise RuntimeError("Missingness must not imply automatic exclusion.")
    censored = separation["source_class"].eq("right_censored_event")
    if not separation.loc[censored, "review_decision"].eq("retained_censored").all():
        raise RuntimeError("Censoring must remain distinct from missingness.")

    (output_dir / "README.md").write_text(_readme(), encoding="utf-8")
    _write_json(
        output_dir / "missing_data_assumptions_manifest.json",
        {
            "example": "18_worked_missing_data_assumptions_audit",
            "evidence_classification": EVIDENCE,
            "source_classes": sorted(SOURCE_CLASSES),
            "missingness_mechanism_inferred": False,
            "mcar_classification_created": False,
            "mar_classification_created": False,
            "mnar_classification_created": False,
            "automatic_complete_case_filtering_performed": False,
            "single_imputation_selected": False,
            "multiple_imputation_selected": False,
            "weighting_method_selected": False,
            "joint_model_selected": False,
            "pattern_mixture_model_selected": False,
            "selection_model_selected": False,
            "survival_estimator_selected": False,
            "glm_glmm_selected": False,
            "sem_selected": False,
            "bayesian_model_selected": False,
            "statistical_model_selected": False,
            "qc_flag_converted_to_exclusion": False,
            "censoring_reclassified_as_missing": False,
            "design_absence_reclassified_as_missing": False,
            "undefined_metric_reclassified_as_missing": False,
            "device_validity_claim_created": False,
            "measurement_validity_claim_created": False,
            "construct_validity_claim_created": False,
            "causal_validity_claim_created": False,
            "psychological_state_claim_created": False,
            "denominator_exposure_clinic": "denominator-exposure-censoring.md",
        },
    )

    print("Worked missing-data assumptions audit complete")
    print(f"Output directory: {output_dir}")
    print("MCAR/MAR/MNAR inferred: no")
    print("Statistical treatment selected: no")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a deterministic missing-data assumptions audit bundle."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("worked-missing-data-assumptions-audit"),
    )
    run(parser.parse_args().output_dir)


if __name__ == "__main__":
    main()
