"""Non-empirical source-inventory scaffolding for prospective VISUS audit copies."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

from .benchmarks import benchmark_fingerprint
from .exceptions import BenchmarkIntegrityError
from .visus_audit import VisusSourceAuditSpec, VisusSourceFileRecord


@dataclass(frozen=True, slots=True)
class VisusSourceAuditScaffold:
    """Exact local inventory paired with a deliberately non-empirical audit specification."""

    root: Path
    spec: VisusSourceAuditSpec
    inventory_fingerprint_sha256: str

    @property
    def file_count(self) -> int:
        """Number of inventoried regular files."""
        return len(self.spec.files)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _inventory(root: Path) -> list[VisusSourceFileRecord]:
    entries = sorted(root.rglob("*"), key=lambda path: path.relative_to(root).as_posix())
    symlinks = [path.relative_to(root).as_posix() for path in entries if path.is_symlink()]
    if symlinks:
        raise BenchmarkIntegrityError(
            "VISUS source scaffold refuses symbolic links because exact snapshot identity must not "
            f"depend on targets outside the reviewed tree: {symlinks}"
        )

    files = [path for path in entries if path.is_file()]
    if not files:
        raise ValueError("VISUS source scaffold requires at least one regular file.")

    records: list[VisusSourceFileRecord] = []
    for path in files:
        relative = path.relative_to(root).as_posix()
        size = int(path.stat().st_size)
        if size <= 0:
            raise BenchmarkIntegrityError(
                "VISUS source scaffold cannot represent zero-byte files in the exact audit "
                f"contract: {relative!r}."
            )
        records.append(
            VisusSourceFileRecord(
                path=relative,
                sha256=_sha256(path),
                bytes=size,
                role="other",
            )
        )
    return records


def build_visus_source_audit_scaffold(root: str | Path) -> VisusSourceAuditScaffold:
    """Inventory a candidate local VISUS tree without inferring scientific identities.

    Every file is intentionally emitted with ``role='other'`` and without stimulus, participant,
    or annotation-stream identities. The returned specification remains
    ``dataset_status='template'`` with all empirical evidence gates unresolved. A researcher must
    manually review and edit those fields before :func:`gazeforge.audit_visus_source` can accept
    the copy as empirical evidence.
    """
    root_path = Path(root)
    if root_path.is_symlink():
        raise BenchmarkIntegrityError(
            "VISUS source scaffold refuses a symbolic-link root because snapshot identity must "
            "refer to the reviewed directory itself."
        )
    if not root_path.is_dir():
        raise FileNotFoundError(f"VISUS candidate source directory does not exist: {root_path}")
    resolved_root = root_path.resolve()
    records = _inventory(resolved_root)
    inventory_rows = [
        {
            "path": record.path,
            "sha256": record.sha256,
            "bytes": int(record.bytes),
            "role": record.role,
        }
        for record in records
    ]
    fingerprint = benchmark_fingerprint(inventory_rows)

    spec = VisusSourceAuditSpec(
        dataset_name="VISUS",
        dataset_version="REPLACE_WITH_REVIEWED_VERSION",
        source="REPLACE_WITH_AUTHORITATIVE_SOURCE",
        source_revision="REPLACE_WITH_SOURCE_REVISION",
        license="REPLACE_WITH_REVIEWED_TERMS",
        reuse_terms_source="REPLACE_WITH_TERMS_SOURCE",
        dataset_status="template",
        reuse_terms_verified=False,
        analysis_use_permitted=False,
        redistribution_status="unknown",
        stimulus_mapping_verified=False,
        stimulus_mapping_basis="",
        participant_mapping_verified=False,
        participant_mapping_basis="",
        coordinate_unit="unverified",
        coordinate_unit_verified=False,
        coordinate_verification_basis="",
        timestamp_basis_verified=False,
        timestamp_verification_basis="",
        independent_annotation_streams_verified=False,
        independent_annotation_streams_basis="",
        files=records,
        notes=[
            "Generated by GazeForge as an inventory-only VISUS audit scaffold.",
            (
                "All files are role='other'; file extensions and names were not used to infer "
                "video/gaze/AOI roles or scientific identities."
            ),
            (
                "Manually review source/reuse/analysis/redistribution, file roles, stimulus and "
                "participant mappings, coordinate units, timestamp/frame-time basis, and any "
                "annotation-stream independence evidence before changing dataset_status."
            ),
            f"Inventory fingerprint at generation time: {fingerprint}",
        ],
    )
    return VisusSourceAuditScaffold(
        root=resolved_root,
        spec=spec,
        inventory_fingerprint_sha256=fingerprint,
    )


def write_visus_source_audit_scaffold(
    scaffold: VisusSourceAuditScaffold,
    path: str | Path,
    *,
    overwrite: bool = False,
) -> Path:
    """Write one loadable template audit-spec JSON outside the inventoried source tree."""
    if not isinstance(scaffold, VisusSourceAuditScaffold):
        raise TypeError("scaffold must be a VisusSourceAuditScaffold instance.")
    target = Path(path)
    resolved_target = target.resolve(strict=False)
    if resolved_target == scaffold.root or scaffold.root in resolved_target.parents:
        raise BenchmarkIntegrityError(
            "VISUS scaffold output must be outside the inventoried source tree so writing the "
            "spec cannot mutate the snapshot it describes."
        )
    if target.exists() and not overwrite:
        raise FileExistsError(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        json.dumps(scaffold.spec.to_dict(), indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    return target
